name: caliscope311
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ffmpeg
  - pip:
    - git+https://github.com/mprib/caliscope.git
    - -e ./tools/calib_record_tool
